package pl.jvng.cryptomarketserverless.repository;

import pl.jvng.cryptomarketserverless.model.Crypto;

import java.util.Arrays;
import java.util.List;

public class CryptoRepository {
    private static List<Crypto> cryptos;

    static {
        cryptos = Arrays.asList(
                new Crypto("Bitcoin", "https://coinmarketcap.com/currencies/bitcoin/"),
                new Crypto("Ethereum", "https://coinmarketcap.com/currencies/ethereum/"),
                new Crypto("Binance Coin", "https://coinmarketcap.com/currencies/binance-coin/"),
                new Crypto("Tether", "https://coinmarketcap.com/currencies/tether/"),
                new Crypto("Solana", "https://coinmarketcap.com/currencies/solana/"),
                new Crypto("Cardano", "https://coinmarketcap.com/currencies/cardano/"),
                new Crypto("USD Coin", "https://coinmarketcap.com/currencies/usd-coin/"),
                new Crypto("XRP", "https://coinmarketcap.com/currencies/xrp/"),
                new Crypto("Polkadot", "https://coinmarketcap.com/currencies/polkadot-new/"),
                new Crypto("Terra Luna", "https://coinmarketcap.com/currencies/terra-luna/"),
                new Crypto("Dogecoin", "https://coinmarketcap.com/currencies/dogecoin/"),
                new Crypto("Shiba INU", "https://coinmarketcap.com/currencies/shiba-inu/"),
                new Crypto("Polygon", "https://coinmarketcap.com/currencies/polygon/"),
                new Crypto("Crypto.com Coin", "https://coinmarketcap.com/currencies/crypto-com-coin/"),
                new Crypto("Binance USD", "https://coinmarketcap.com/currencies/binance-usd/"),
                new Crypto("Wrapped Bitcoin", "https://coinmarketcap.com/currencies/wrapped-bitcoin/"),
                new Crypto("Uniswap", "https://coinmarketcap.com/currencies/uniswap/"),
                new Crypto("Hedera", "https://coinmarketcap.com/currencies/hedera/"),
                new Crypto("The Sandbox", "https://coinmarketcap.com/currencies/the-sandbox/"),
                new Crypto("Theta", "https://coinmarketcap.com/currencies/theta/"),
                new Crypto("Near Protocol", "https://coinmarketcap.com/currencies/near-protocol/"),
                new Crypto("Chain Link", "https://coinmarketcap.com/currencies/chainlink/"),
                new Crypto("Tron", "https://coinmarketcap.com/currencies/tron/"),
                new Crypto("Bitcoin Cash", "https://coinmarketcap.com/currencies/bitcoin-cash/"),
                new Crypto("TerraUSD", "https://coinmarketcap.com/currencies/terrausd/"),
                new Crypto("Stellar", "https://coinmarketcap.com/currencies/stellar/"),
                new Crypto("Decentraland", "https://coinmarketcap.com/currencies/decentraland/"),
                new Crypto("Dai", "https://coinmarketcap.com/currencies/multi-collateral-dai/"),
                new Crypto("Axie Infinity", "https://coinmarketcap.com/currencies/axie-infinity/"),
                new Crypto("FTX token", "https://coinmarketcap.com/currencies/ftx-token/"),
                new Crypto("VeChain", "https://coinmarketcap.com/currencies/vechain/"),
                new Crypto("Elrond", "https://coinmarketcap.com/currencies/elrond-egld/"),
                new Crypto("Internet Computer", "https://coinmarketcap.com/currencies/internet-computer/"),
                new Crypto("Bitcoin BEP2", "https://coinmarketcap.com/currencies/bitcoin-bep2/"),
                new Crypto("Filecoin", "https://coinmarketcap.com/currencies/filecoin/"),
                new Crypto("Kusama", "https://coinmarketcap.com/currencies/kusama/"),
                new Crypto("eCash", "https://coinmarketcap.com/currencies/ecash/"),
                new Crypto("Fantom", "https://coinmarketcap.com/currencies/fantom/"),
                new Crypto("Monero", "https://coinmarketcap.com/currencies/monero/"),
                new Crypto("Tezos", "https://coinmarketcap.com/currencies/tezos/"),
                new Crypto("Unus Sed Leo", "https://coinmarketcap.com/currencies/unus-sed-leo/"),
                new Crypto("Klatyn", "https://coinmarketcap.com/currencies/klaytn/"),
                new Crypto("Gala", "https://coinmarketcap.com/currencies/gala/"),
                new Crypto("The Graph", "https://coinmarketcap.com/currencies/the-graph/"),
                new Crypto("Helium", "https://coinmarketcap.com/currencies/helium/"),
                new Crypto("Iota", "https://coinmarketcap.com/currencies/iota/"),
                new Crypto("EOS", "https://coinmarketcap.com/currencies/eos/"),
                new Crypto("Pancake SWAP", "https://coinmarketcap.com/currencies/pancakeswap/"),
                new Crypto("Loop RIng", "https://coinmarketcap.com/currencies/loopring/"),
                new Crypto("Flow", "https://coinmarketcap.com/currencies/flow/"),
                new Crypto("Stacks", "https://coinmarketcap.com/currencies/stacks/"),
                new Crypto("BitTorrent", "https://coinmarketcap.com/currencies/bittorrent/"),
                new Crypto("Maker", "https://coinmarketcap.com/currencies/maker/"),
                new Crypto("Bitcoin SV", "https://coinmarketcap.com/currencies/bitcoin-sv/"),
                new Crypto("Aave", "https://coinmarketcap.com/currencies/aave/"),
                new Crypto("ZCash", "https://coinmarketcap.com/currencies/zcash/"),
                new Crypto("Enjin Coin", "https://coinmarketcap.com/currencies/enjin-coin/"),
                new Crypto("AMP", "https://coinmarketcap.com/currencies/amp/"),
                new Crypto("Quant", "https://coinmarketcap.com/currencies/quant/"),
                new Crypto("Waves", "https://coinmarketcap.com/currencies/waves/"),
                new Crypto("Neo", "https://coinmarketcap.com/currencies/neo/"),
                new Crypto("Harmony", "https://coinmarketcap.com/currencies/harmony/"),
                new Crypto("Basic Attention Token", "https://coinmarketcap.com/currencies/basic-attention-token/"),
                new Crypto("ThorChain", "https://coinmarketcap.com/currencies/thorchain/"),
                new Crypto("Chiliz", "https://coinmarketcap.com/currencies/chiliz/"),
                new Crypto("Kadena", "https://coinmarketcap.com/currencies/kadena/"),
                new Crypto("Kucoin Token", "https://coinmarketcap.com/currencies/kucoin-token/"),
                new Crypto("Holo", "https://coinmarketcap.com/currencies/holo/"),
                new Crypto("Curve DAO", "https://coinmarketcap.com/currencies/curve-dao-token/"),
                new Crypto("Arwe ave", "https://coinmarketcap.com/currencies/arweave/"),
                new Crypto("Huobi Token", "https://coinmarketcap.com/currencies/huobi-token/"),
                new Crypto("Dash", "https://coinmarketcap.com/currencies/dash/"),
                new Crypto("Com pound", "https://coinmarketcap.com/currencies/compound/"),
                new Crypto("Celo", "https://coinmarketcap.com/currencies/celo/"),
                new Crypto("Theta Fuel", "https://coinmarketcap.com/currencies/theta-fuel/"),
                new Crypto("TrueUSD", "https://coinmarketcap.com/currencies/trueusd/"),
                new Crypto("Decred", "https://coinmarketcap.com/currencies/decred/"),
                new Crypto("Nexo", "https://coinmarketcap.com/currencies/nexo/"),
                new Crypto("NEM", "https://coinmarketcap.com/currencies/nem/"),
                new Crypto("Mina", "https://coinmarketcap.com/currencies/mina/"),
                new Crypto("IoTex", "https://coinmarketcap.com/currencies/iotex/"),
                new Crypto("Voyager Token", "https://coinmarketcap.com/currencies/voyager-token/"),
                new Crypto("1inch Network", "https://coinmarketcap.com/currencies/1inch/"),
                new Crypto("Qtum", "https://coinmarketcap.com/currencies/qtum/"),
                new Crypto("Pax dollar", "https://coinmarketcap.com/currencies/paxos-standard/"),
                new Crypto("Immutable X", "https://coinmarketcap.com/currencies/immutable-x/"),
                new Crypto("XDC Network", "https://coinmarketcap.com/currencies/xinfin/"),
                new Crypto("Ravencoin", "https://coinmarketcap.com/currencies/ravencoin/"),
                new Crypto("Celsius", "https://coinmarketcap.com/currencies/celsius/"),
                new Crypto("Ankr", "https://coinmarketcap.com/currencies/ankr/"),
                new Crypto("Wax", "https://coinmarketcap.com/currencies/wax/")
        );
    }

    public static List<Crypto> getCryptos() {
        return cryptos;
    }

}
